language: python
python:
  - "3.7"
os: linux
dist: bionic
addons:
  postgresql: "11"
  apt:
    packages:
      - language-pack-de
services:
  - redis
cache: pip
install:
  - "pip install --upgrade pip"
  # Should prevent https://github.com/pypa/setuptools/issues/3118
  - "pip install setuptools==60.8.2"
  - "pip install -r requirements.txt -r requirements-test.txt"
before_script:
  - psql -U postgres -c "CREATE DATABASE byceps_test;"
  - psql -U postgres -c "CREATE ROLE byceps_test WITH LOGIN PASSWORD 'test';"
script:
  - "pytest"
notifications:
  email: false
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - bash ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - bash ./send.sh failure $WEBHOOK_UR
